### ISSUE TITLE
Error on building io.github.aerocyber.sitemarker

### ISSUE THREAD

**Issue by aerocyber** [flathub/flathub#4517]
Hi, I've updated my application and as part of it, **removed a few unnecessary permissions.** However, I am getting **buildbot errors.** The application is written in **Python** with **GTK4** and uses **GNOME SDK 44**. I tried building it **locally** and it was **successful.**

I hope to be helped in resolving the same.

Buildbot link: [66056](https://buildbot.flathub.org/#/builders/6/builds/66056)

Buildbot exception:

```
Traceback (most recent call last):
  File "/var/lib/buildbot-master/sandbox/lib/python3.10/site-packages/twisted/internet/defer.py", line 891, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/var/lib/buildbot-master/sandbox/lib/python3.10/site-packages/twisted/internet/defer.py", line 1791, in gotResult
    _inlineCallbacks(r, gen, status, context)
  File "/var/lib/buildbot-master/sandbox/lib/python3.10/site-packages/twisted/internet/defer.py", line 1692, in _inlineCallbacks
    result = context.run(
  File "/var/lib/buildbot-master/sandbox/lib/python3.10/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/var/lib/buildbot-master/sandbox/lib/python3.10/site-packages/buildbot/process/buildstep.py", line 628, in startStep
    self.results = yield self.run()
  File "/var/lib/buildbot-master/sandbox/lib/python3.10/site-packages/twisted/internet/defer.py", line 1696, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/var/lib/buildbot-master/sandbox/lib/python3.10/site-packages/buildbot/flathub_master.py", line 977, in run
    defer.returnValue(downloadd_cmd.results())
builtins.NameError: name 'downloadd_cmd' is not defined
```

**Comment by hfiguiere** [comment]
The actual error on stdio is :

```
FB: Running: git rev-parse 1.2.3
FB: Running: git rev-parse --verify --quiet 203a6139671555f5df47faf4d8e5633cfd112373:.gitmodules
FB: Running: git rev-parse 1.2.3
FB: Running: git rev-parse '1.2.3^{commit}'
Failed to download sources: module sitemarker: Git commit for branch (null) is 203a6139671555f5df47faf4d8e5633cfd112373, but expected 59c122a804b6a69efe4569f38906e718705914de
program finished with exit code 1
```

**Comment by hfiguiere** [comment]
So you would get the error regardless it's just there is an error in the error handling code.

@barthalion needs to fix it.

**Comment by aerocyber** [comment]
Alright, thank you for your help! It was a mistake on my part (incorrect tag). Changing it did fix it.
