### ISSUE TITLE
Liferea can't display articles

### ISSUE THREAD

**Issue by sionescu** [flathub/flathub#4615]
It used to work fine until recently. Now I'm getting this error:

```
$ flatpak run net.sourceforge.liferea
Gtk-Message: 09:44:28.457: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:44:28.492: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:44:28.493: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:44:28.618: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:44:28.648: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:44:28.649: Failed to load module "canberra-gtk-module"

** (liferea:2): WARNING **: 09:44:28.748: Error importing plugin 'webkitsetting':
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/hechee/.var/app/net.sourceforge.liferea/data/liferea/plugins/webkit-setting/webkitsetting.py", line 42, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib/python3.11/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace WebKit2 not available for version 4.0

(liferea:2): libpeas-WARNING **: 09:44:28.748: Error loading plugin 'webkitsetting'
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 938x364: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 938x364: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 938x364: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1

(liferea:2): Gdk-CRITICAL **: 09:44:29.480: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(liferea:2): Gdk-CRITICAL **: 09:44:30.099: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(liferea:2): Gdk-CRITICAL **: 09:44:30.239: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed
```

**Comment by razzeee** [comment]
should be raised in https://github.com/flathub/net.sourceforge.liferea
