### ISSUE TITLE
org.gaphor.Gaphor Builds are Failing on FlatHub BuildBot

### ISSUE THREAD

**Issue by danyeaw** [flathub/flathub#957]
I am trying to resolve https://github.com/gaphor/gaphor/issues/135.

I can successfully build my org.gaphor.Gaphor flatpak locally. When I create a [Pull Request](https://github.com/flathub/org.gaphor.Gaphor/pull/2) with the same manifest I am getting the following build error on all platforms:

```
HEAD is now at 9c6604f Add setuptools to dependencies
FB: Running: git rev-parse --verify --quiet 1.0.0.post2:.gitmodules
]2;flatpak-builder: Installing gaphorRunning: pip3 install --prefix=/app --disable-pip-version-check --no-build-isolation --no-deps .
FB: Running: flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/gaphor --nofilesystem=host --filesystem=/srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/build/gaphor-1 --bind-mount=/run/build/gaphor=/srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/build/gaphor-1 --build-dir=/run/build/gaphor --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1554777395 '--env=CFLAGS=-march=x86-64 -mtune=generic -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' '--env=CXXFLAGS=-march=x86-64 -mtune=generic -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed' --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-uP2Rks /bin/sh -c 'pip3 install --prefix=/app --disable-pip-version-check --no-build-isolation --no-deps .'
Processing /run/build/gaphor
    Preparing wheel metadata ... [?25ldone
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "/usr/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 528, in prepare_metadata
    self.prepare_pep517_metadata()
  File "/usr/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 573, in prepare_pep517_metadata
    metadata_dir
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 86, in prepare_metadata_for_build_wheel
    'config_settings': config_settings,
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
    raise BackendUnavailable
pip._vendor.pep517.wrappers.BackendUnavailable
[?25h]2;flatpak-builder: Cleanup gaphorError: module gaphor: Child process exited with code 2
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-uP2Rks
program finished with exit code 1
elapsedTime=32.945094
```

I think there is an issue here with pip where the are hiding most of the debug information, but I could use some help in approaching the best way to debug this on the BuildBot infrastructure. On a [pip issue](https://github.com/pypa/pip/issues/6100) for a similar problem, there is guidance on how to edit the `_in_process` module in order to enable a full traceback.

**Comment by danyeaw** [comment]
I am now able to reproduce this error locally after completely reinstalling flatpak and flatpak-builder. The setup instructions for Ubuntu are wrong on the website, users of recent releases of Ubuntu should be using the repository packages. This is related to: https://github.com/flatpak/flatpak.github.io/issues/319. I will try to submit a PR to correct this.

The issue with BackendUnavailable is related to issue https://github.com/pypa/setuptools/issues/1644. In order to get it to work:
- Add setuptools and wheel as build-system requires packages in my pyproject.toml
- Install setuptools, wheel, and poetry and all of their dependencies at the exact same pip install step as installing Gaphor itself (and it's dependencies).

The builds are now passing again :tada: 

I am down to one more issue:
- The app runs fine when I apply the `--socket=session-bus` permission option. But I am getting the following error without giving access to the session-bus:
```(flatpak run:29910): flatpak-DEBUG: 15:10:31.198: Running '/usr/lib/flatpak/flatpak-bwrap --args 33 gaphor'
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
(process:29918): flatpak-DEBUG: 15:10:31.682: Error reading from socket: Error receiving message: Connection reset by peer
```
This is the session-bus log:
```
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
C2: -> org.freedesktop.DBus fake wildcarded AddMatch for org.mpris.MediaPlayer2.org.gaphor.Gaphor
C3: -> org.freedesktop.DBus fake AddMatch for ca.desrt.dconf
C4: -> org.freedesktop.DBus fake GetNameOwner for ca.desrt.dconf
C5: -> org.freedesktop.DBus fake wildcarded AddMatch for org.gaphor.Gaphor
C6: -> org.freedesktop.DBus fake wildcarded AddMatch for org.freedesktop.portal
C7: -> org.freedesktop.DBus fake ListNames
B1: <- org.freedesktop.DBus return from C1
B2: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B3: <- org.freedesktop.DBus return from C2
*SKIPPED*
B4: <- org.freedesktop.DBus return from C3
*SKIPPED*
B5: <- org.freedesktop.DBus return from C4
*SKIPPED*
B6: <- org.freedesktop.DBus return from C5
*SKIPPED*
B7: <- org.freedesktop.DBus return from C6
*SKIPPED*
B8: <- org.freedesktop.DBus return from C7
C8: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.DBus
C9: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Desktop
C10: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Documents
C11: -> org.freedesktop.DBus fake GetNameOwner for ca.desrt.dconf
C12: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.IBus
*SKIPPED*
B9: <- org.freedesktop.DBus return from C8
*SKIPPED*
B10: <- org.freedesktop.DBus return from C9
*SKIPPED*
B11: <- org.freedesktop.DBus return from C10
*SKIPPED*
B12: <- org.freedesktop.DBus return from C11
*SKIPPED*
B13: <- org.freedesktop.DBus return from C12
*SKIPPED*
C13: -> org.freedesktop.DBus call org.freedesktop.DBus.RequestName at /org/freedesktop/DBus
Filtering message due to arg0 org.gaphor.gaphor, policy: 0 (required 3)
*HIDDEN* (ping)
B14: <- (no sender) return from C13
*REWRITTEN*
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
(process:29962): flatpak-DEBUG: 15:11:33.900: Error reading from socket: Error receiving message: Connection reset by peer
```

**Comment by danyeaw** [comment]
The DBus Error was caused by the application id being org.gaphor.gaphor instead of org.gaphor.Gaphor.
